name: Nominator CI for homeless

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build nominator
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build 
          build-root-directory: nominator
      - name: Build fiscal
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build 
          build-root-directory: fiscal
      - name: Install user input simulation packages
        run: |
          sudo apt-get install expect
      - name: Start LocalStack
        run: |
          pip install pip --upgrade
          pip install pyopenssl --upgrade
          pip install localstack awscli-local       # install LocalStack cli and awslocal
          docker pull localstack/localstack         # Make sure to pull the latest version of the image
          localstack start -d                       # Start LocalStack in the background

          echo "Waiting for LocalStack startup..."  # Wait 30 seconds for the LocalStack container
          localstack wait -t 30                     # to become ready before timing out
          echo "Startup complete"
      - name: Gear up pseudo aws stack
        env:
          USER_SIMULATION_SKETCH: dev-tools/deployment/user-simulation-infra-stack.exp
        run: |
          cd $(dirname $USER_SIMULATION_SKETCH)
          INCEPT_CMD=$(./$(basename $USER_SIMULATION_SKETCH))
          $INCEPT_CMD >> $GITHUB_OUTPUT
          cd -
      - name: Execute verification for the pseudo aws stack
        env:
          VERIFICATION_PSEUDO_STACK: dev-tools/deployment/verify-infra-stack.sh
        run: |
          cd $(dirname $VERIFICATION_PSEUDO_STACK)
          ./$(basename $VERIFICATION_PSEUDO_STACK) >> $GITHUB_OUTPUT
          cd -
